### ISSUE TITLE
DeprecationWarning: firefox_profile has been deprecated

### ISSUE THREAD

**Issue by DAVIDbNYC** [interlark/ustvgo-iptv#23]
I tried to install the same script that I had been using successfully on my old PC and am getting a depreciation warning.  Is there a fix?

David

david@HP-ENVY:~/ustvgo_downloader$ ./download.py
Downloading the playlist, please wait...
/home/david/ustvgo_downloader/./download.py:109: DeprecationWarning: firefox_profile has been deprecated, please use an Options object
  firefox_profile = webdriver.FirefoxProfile()
Traceback (most recent call last):
  File "/home/david/ustvgo_downloader/./download.py", line 129, in <module>
    with webdriver.Firefox(seleniumwire_options=set_seleniumwire_options, options=ff_options, firefox_profile=firefox_profile) as driver:
  File "/home/david/.local/lib/python3.10/site-packages/seleniumwire/webdriver/browser.py", line 46, in __init__
    super().__init__(*args, **kwargs)
  File "/home/david/.local/lib/python3.10/site-packages/selenium/webdriver/firefox/webdriver.py", line 175, in __init__
    self.service.start()
  File "/home/david/.local/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/home/david/.local/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 110, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service geckodriver unexpectedly exited. Status code was: 64

**Comment by interlark** [comment]
New code is not based on browser drivers anymore, so I can mark this issue resolved.

**Comment by DAVIDbNYC** [comment]
The new code rocks!  Thank you.Sent from my T-Mobile 5G DeviceGet Outlook for Android
