### ISSUE TITLE
Crashes after an hour or so of runtime

### ISSUE THREAD

**Issue by jxm90** [interlark/ustvgo-iptv#25]
I keep getting a crash. Here is the output

15:30:12 :: ERROR :: SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f1f107ad6d8>
transport: <_SelectorSocketTransport fd=10 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)

**Comment by interlark** [comment]
I think I met this bug before, it happens in python 3.7, it was fixed in python 3.7.4.
You got 2 solutions here: ignore it or upgrade python from 3.7 to 3.7.4

**Comment by interlark** [comment]
Yup, I can reproduce it with python 3.7.0, but errors disappears starting from python 3.7.4.
Issue is closed as it could be fixed by python upgrading.
