### ISSUE TITLE
More a question?

### ISSUE THREAD

**Issue by KraftBurner71** [interlark/ustvgo-iptv#28]
Adding m3u and xmltv ips to Next PVR. Guide and links are present but keep getting the following . . .

>>>
08:07:01 | [Retry 1/2] Error occured during handling request: Cannot connect to host h4.ustvgo.la:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)')]
Traceback (most recent call last):
  File "aiohttp\connector.py", line 986, in _wrap_create_connection
  File "asyncio\base_events.py", line 1089, in create_connection
  File "asyncio\base_events.py", line 1119, in _create_connection_transport
  File "asyncio\sslproto.py", line 534, in data_received
  File "asyncio\sslproto.py", line 188, in feed_ssldata
  File "ssl.py", line 975, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "ustvgo_iptv\ustvgo_iptv.py", line 232, in stream_handler
  File "aiohttp\client.py", line 1186, in __aenter__
  File "aiohttp\client.py", line 535, in _request
  File "aiohttp\connector.py", line 542, in connect
  File "aiohttp\connector.py", line 907, in _create_connection
  File "aiohttp\connector.py", line 1206, in _create_direct_connection
  File "aiohttp\connector.py", line 1175, in _create_direct_connection
  File "aiohttp\connector.py", line 988, in _wrap_create_connection
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host h4.ustvgo.la:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)')]

Am I doing anything wrong? How can I go about getting the SSL cert to verify properly?

**Comment by interlark** [comment]
I believe certificate verification could fail for a couple of reasons, like wrong local time, expired root CA, etc.
I've been thinking about turning off SSL verification before, because no need in it during watching IPTV.

**Comment by KraftBurner71** [comment]
Let me know if and when you do and I will retest.

**Comment by interlark** [comment]
You can test [changes](https://github.com/interlark/ustvgo-iptv/commit/38199b48bd6a2e4bea709c79acacb86daf3f0849) with dev build [here](https://github.com/interlark/ustvgo-iptv/actions/runs/2695689413).

**Comment by KraftBurner71** [comment]
Using the Dev version worked . . . tested several scenarios with and without VPN on/

**Comment by interlark** [comment]
Ok, thanks for testing. SSL verification will be disabled in v0.1.7 soon.
