### ISSUE TITLE
Win GUI - Unhandled Exception in Script

### ISSUE THREAD

**Issue by TJ-00-TJ** [interlark/ustvgo-iptv#37]
I just started getting this error when running through the Win GUI v0.1.9 a few days ago

Unhandled Exception in Script

Failed to execute script 'main' due to unhandled exception:
Expecting value line 1 column 1 (char 0)

Traceback (most recent call last):
  File "main.py", line 14, in <module>
  File "main.py", line 10, in main
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 616, in run_until_complete
  File "gui\app.py", line 22, in app
  File "gui\settings.py", line 25, in load_settings
  File "json\__init__.py", line 357, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by interlark** [comment]
That's odd.
Delete config file **config file** on following path:

  * **Linux**: ~/.config/ustvgo-iptv/settings.cfg
  * **Mac**: ~/Library/Application Support/ustvgo-iptv/settings.cfg
  * **Windows**: C:\Users\\%USERPROFILE%\AppData\Local\ustvgo-iptv\settings.cfg

Gonna fix it in the next release.
I don't know how this could happen to you, but it looks like config file got corrupted somehow.

**Comment by TJ-00-TJ** [comment]
Thanks - all fixed. Appreciate all the hard work you've put into this - great little application.
